import * as TablerIcons from '@tabler/icons-react'
import type { ComponentType } from 'react'

export interface TablerIconProps {
	size?: number
	color?: string
	stroke?: number
}

const registry = TablerIcons as unknown as Record<string, ComponentType<TablerIconProps>>

/** Every outline icon's component name (e.g. "IconHome"), sorted. Filled variants are excluded. */
export const tablerIconNames: readonly string[] = Object.keys(registry)
	.filter((name) => name.startsWith('Icon') && !name.endsWith('Filled'))
	.sort()

export function getTablerIcon(name: string): ComponentType<TablerIconProps> | undefined {
	return registry[name]
}

/** The icon's solid-fill counterpart (its own closed-path artwork, not a background
 *  shape), e.g. "IconHome" -> "IconHomeFilled". Only a subset of icons have one. */
export function getTablerFilledIcon(name: string): ComponentType<TablerIconProps> | undefined {
	return registry[`${name}Filled`]
}

/** A search-friendly label: "IconLockAccess" -> "lock access". */
export function tablerIconLabel(name: string): string {
	return name
		.slice('Icon'.length)
		.replace(/([a-z0-9])([A-Z])/g, '$1 $2')
		.replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
		.toLowerCase()
}

// Extra keywords per icon ("IconTrash" -> "bin delete garbage …"), generated by
// scripts/icon-tags.js. About 450KB, so loaded on demand (see loadTablerTags), not at startup.
let tags: Record<string, string> | null = null
let tagsLoading: Promise<void> | null = null

/** Loads the icons' search keywords; searches before it resolves match names only. */
export function loadTablerTags(): Promise<void> {
	tagsLoading ??= import('./tabler-tags.json').then((module) => {
		tags = module.default
		searchEntries = null // rebuilt with the tags on the next search
	})
	return tagsLoading
}

interface SearchEntry {
	name: string
	label: string
	words: string[]
	/** Keyword tags split into words ("ash-bin" gives "ash" and "bin"). */
	tagWords: string[]
}

// Worked out once rather than per keystroke (there are 5,000+ icons), and only on the first
// search, since this module loads at startup for the icon shape.
let searchEntries: SearchEntry[] | null = null
function getSearchEntries() {
	searchEntries ??= tablerIconNames.map((name) => {
		const label = tablerIconLabel(name)
		return { name, label, words: label.split(' '), tagWords: tags?.[name]?.split(/[\s-]+/) ?? [] }
	})
	return searchEntries
}

/**
 * How well one search term matches an icon, lower being better, or null for no match. Its name
 * first: the first word exactly, then the start of the first word, then any whole word, then
 * the start of any word. So "star" puts "star" and "star half", then "stars", ahead of "folder
 * star". Then its keyword tags ("delete" finds "trash"), which are looser, so they rank below
 * any name match. Last, the term anywhere in the name ("brand kickstarter").
 */
function termRank({ words, label, tagWords }: SearchEntry, term: string): number | null {
	if (words[0] === term) return 0
	if (words[0].startsWith(term)) return 1
	if (words.includes(term)) return 2
	if (words.some((word) => word.startsWith(term))) return 3
	if (tagWords.includes(term)) return 4
	if (tagWords.some((word) => word.startsWith(term))) return 5
	if (label.includes(term)) return 6
	return null
}

/** Icon names matching every word of `query`, best matches first. */
export function searchTablerIcons(query: string): readonly string[] {
	const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean)
	if (terms.length === 0) return tablerIconNames

	const results: { name: string; rank: number; wordCount: number }[] = []
	for (const entry of getSearchEntries()) {
		const { name, label } = entry
		let worst = 0
		for (const term of terms) {
			const rank = termRank(entry, term)
			if (rank === null) {
				worst = -1
				break
			}
			worst = Math.max(worst, rank)
		}
		if (worst === -1) continue
		// The exact name beats everything. Among equal matches, plain icons ("settings") come
		// before their variants ("settings 2", "eye cog"); not shorter names first, which put
		// "shirt" (tagged "gear" as in clothing) ahead of "settings" for "gear".
		results.push({ name, rank: label === terms.join(' ') ? -1 : worst, wordCount: entry.words.length })
	}
	// Stable sort, so remaining ties keep the list's alphabetical order.
	results.sort((a, b) => a.rank - b.rank || a.wordCount - b.wordCount)
	return results.map((result) => result.name)
}
